spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml